### ISSUE TITLE
How the imitation-learning model is trained?

### ISSUE THREAD

**Issue by Yifei-Wei** [omarrayyann/mujoco_fruits_picking#1]
Hi，dear omarrayyann，I really wonder how the imitation-learning model is trained for the fruit picking project . Because the dataset provided is npz file , and I dont understand how actually it works for the training .

**Comment by omarrayyann** [comment]
Hello @Yifei-Wei. Check out the training framework [here](https://github.com/omarrayyann/mujoco_fruits_picking/tree/main/Model). Let me know if you have any further questions.

**Comment by Yifei-Wei** [comment]
Thanks for your reply, I haved found the training framework just after I raise this issue ,so i closed it immediately QAQ  . 
I have another question just after reading the traning code .
Do you get the training-dataset(expertise examples) by just given the location of the fruits and make the iiwa14 pick it directly so that you can record this process and make it into the npz file?

**Comment by omarrayyann** [comment]
No, I used teleoperation to collect the data. More precisely, I used [mujoco_ar](https://github.com/omarrayyann/MujocoAR/tree/main). It allows you to controls the robot using your phone pose. Try it out.

**Comment by Yifei-Wei** [comment]
That`s amazing ,  i will try it now.

**Comment by omarrayyann** [comment]
by the way it's already setup on this project. download the app called "mujoco ar" from the app store, then when you run the ```main.py``` from this project, you will be given an ip address and a port number. Enter those on the app and you should be able to directly control the robot

**Comment by Yifei-Wei** [comment]
emmm , I have just found that mujoco_ar only supports IOS system ......   Do you have a Android version for the mujoco_ar? 
I am using the Android phone .

**Comment by omarrayyann** [comment]
unfortunately there's no android version at the moment

**Comment by Yifei-Wei** [comment]
all right . I will try to borrow one from my friend. All in all ,thanks for your reply and your patience. Appreciate.
